-- WCFDI validation lua script (auto-generated by harness.py).
--
-- Drives the brucon RunFastStandalone simulator through:
--   1. Set environment (wave + wind + current) at constant compass direction
--   2. Hold the vessel still via SetFixedCourseAndSpeed(0, 0, true) for
--      PRECONDITION_S seconds while sensors / posrefs / observers settle
--      (the vessel_simulator comment explicitly recommends this pattern
--       for RunFast: "such that signal processing is happy and control
--       system can be activated with no waiting").
--   3. Release the fix and immediately activate station keeping.
--   4. Settle for SETTLE_S seconds of free intact-DP operation -- this is
--      the window we sample for the steady-state intact-footprint stats.
--   5. At t = FAILURE_T (relative to script start), kill the failed thrusters.
--   6. Continue for POST_FAILURE_S seconds with the WCFDI in effect.
--
-- All placeholders are replaced by Python harness.render_lua().
--
-- Coordinate convention: SetWaveCondition(direction) is "from" compass bearing
-- in degrees. SetVesselSimulatorHeading is vessel heading (compass, deg).

local last_str = ''
local function iop(str)
   io.write(('\\b \\b'):rep(#last_str))
   io.write(str)
   io.flush()
   last_str = str
end

-- ---- Output ----
SetOutputFile('{output_file}')
SetOutputFileEstimator('{estimator_output_file}')

-- ---- Reproducibility ----
SetWaveRandomSeed({wave_seed})

-- ---- Environment (constant throughout the run) ----
SetWaveCondition({Hs}, {Tp}, {wave_dir_compass})
SetWindCondition({wind_speed}, {wind_dir_compass})
SetCurrentCondition({current_speed}, {current_dir_compass})

-- ---- Initial state ----
SetVesselSimulatorHeading({vessel_heading_compass})

-- ---- Hold the vessel still while sensors/observers precondition ----
SetFixedCourseAndSpeed(0, 0, true)

-- ---- Run loop (10 Hz) ----
local n_total = {n_total_steps}        -- total simulator steps
local i_release  = {i_release_fixed}   -- step index to release SetFixedCourseAndSpeed
local i_sk       = {i_activate_sk}     -- step index to activate station keeping (= i_release + 1 step)
local i_fail     = {i_failure}         -- step index to inject WCFDI
local print_every = {print_every}      -- how often to PrintDataLine (>=1)

iop('From Lua: starting validation run -> ' .. '{output_file}' .. '\n')

for i = 0, n_total do
    if (i == i_release) then
        iop('From Lua: t=' .. (0.1 * i) .. 's, releasing fixed course/speed\n')
        SetFixedCourseAndSpeed(0, 0, false)
    end

    if (i == i_sk) then
        iop('From Lua: t=' .. (0.1 * i) .. 's, activating station keeping\n')
        SetStationKeeping()
        -- Pin runtime gain level to kMedium (0=Relaxed, 1=Low, 2=Medium, 3=High).
        -- This guarantees the proto-level omega values in
        -- ~/src/brucon/build/bin/settings/tuning.prototxt
        --   pid_surge.omega = 0.06, pid_sway.omega = 0.08, pid_yaw.omega = 0.12
        -- are applied at full scale (gain_level_scaling.relaxed=0.4,low=0.8,high=1.2
        -- would otherwise alter the effective bandwidth at startup defaults).
        SetControllerGainLevel(2, 2, 2)
    end

    if (i == i_fail) then
        iop('From Lua: t=' .. (0.1 * i) .. 's, injecting WCFDI (deactivating thrusters)\n')
{failure_lines}
    end

    Step()

    if (i % print_every == 0) then
        PrintDataLine()
    end
end

CloseOutputFile()
iop('From Lua: validation run done\n')
